# Generated by Django 5.1 on 2024-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="adress",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="company",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, upload_to="company_logo"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="www",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="emploeyy",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="emploeyy",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="emploeyy",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
