# Generated by Django 5.1 on 2024-08-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_emploeyy_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="emploeyy",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
            ),
            preserve_default=False,
        ),
    ]
